# Site settings
title: Ric Santos
email: rics@ntos.me
url: https://ricsantos.github.io/
description: "Ric Santos, an Adelaide, Australia, based iOS mobile app developer."
keywords: "ric santos, adelaide, australia, ios, mobile, developer"
skills: "Mobile App Developer"
meta_author: Santos Ric

# fix baseurl: https://stackoverflow.com/a/25466367/883413
baseurl: /

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
# https://coolors.co/909cc2-084887-f58a07-f9ab55-f7f5fb
color:
  light-blue: 909CC2
  dark-blue: 084887
  orange: F58A07
  light-orange: F9AB55
  primary: 803D57 #532035 #D9D1C9 #80B3FF // header
  # primary-rgb: "24,288,156" #"128,179,255"
  secondary: 555555 #FD6E8A   // nav bar, location
  secondary-dark: 333333 #A2122F  // footer
  link: DDDDDD

# Footer settings
footer:
  copyright: Ric Santos
  location: Location
  social: Social
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rixantos
  - title: facebook
    url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
  - title: stack-overflow
    url: https://stackoverflow.com/users/883413/ric-santos
  - title: linkedin
    url: https://www.linkedin.com/in/rsantos/
  #- title: bitbucket
  #  url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/ricsantos

# Postal address (add as many lines as necessary)
address:
  - line: Adelaide, Australia
  #- line: Beverly Hills, CA 90210

# Credits content
credits: 'Theme forked from <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
